/**
 * Author : Abhirami R Iyer
 */
package apiendpoints;

import aiservice.LlmService;
import com.fasterxml.jackson.databind.JsonNode;
import data.WhiteBoardData;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import request.AiDescriptionRequest;
import request.AiRegularisationRequest;
import request.AiRequestable;
import response.AiResponse;
import request.AiInsightsRequest;
import request.AiSummarisationRequest;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Executor;
import java.util.concurrent.TimeUnit;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * REST controller for AI-based image processing services.
 * Handles interpretation and regularisation requests.
 */
@RestController
@RequestMapping("/api")
public class AiServiceController {

    @Autowired
    private AsyncAiExecutor asyncExecutor;

    /**
     * Interprets an uploaded image and generates a textual description.
     *
     * @param file uploaded image file (from client)
     * @return textual description of the image
     */
    @PostMapping("/image/interpret")
    public CompletableFuture<ResponseEntity<String>> describe(
            @RequestParam("file") final MultipartFile file) {
            try {
                Path tempFile = null;
                // Save uploaded file temporarily
                tempFile = Files.createTempFile(
                        "upload-", "-" + file.getOriginalFilename());
                file.transferTo(tempFile.toFile());

                // Pass file path to your existing data class
                WhiteBoardData data = new WhiteBoardData(tempFile.toString());
                Path finalTempFile = tempFile;
                return asyncExecutor.execute(new AiDescriptionRequest(data))
                        .whenComplete((r, ex) -> {
                            try { Files.deleteIfExists(finalTempFile); } catch (Exception ignored) {}
                        });
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
    }

    /**
     * Regularises a set of input points to produce a smoother output.
     *
     * @param points JSON string containing the points data
     * @return regularised point data as a response
     */
    @PostMapping("/image/regularise")
    public  CompletableFuture<ResponseEntity<String>> regularise(final @RequestBody String points) {
        try {
            return asyncExecutor.execute(new AiRegularisationRequest(points));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * API for sentiment analysis.
     * Recieves chats as a json file, does sentiment analysis,
     * and generates insights graph
     * @param chatData JSON object containing the chat data
     * @return a list float values to plot in the sentiment graph.
     */
    @PostMapping("/chat/sentiment")
    public  CompletableFuture<ResponseEntity<String>> sentiment(
            final @RequestBody JsonNode chatData){
        try {
            return asyncExecutor.execute(new AiInsightsRequest(chatData));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
    /**
     * Summarises chat-based text content asynchronously.
     *
     * @param jsonContent the chat messages in JSON format
     * @return summary text generated by the AI
     */
    @PostMapping("/text/summarise")
    public CompletableFuture<ResponseEntity<String>> summariseText(
            @RequestBody final String jsonContent) {
        try {
            return asyncExecutor.execute(new AiSummarisationRequest(jsonContent));
        } finally {

        }
    }
}
